apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: weather-app-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: weather-app-config
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: weather-app-config
                  key: BACKEND_PORT
