kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
    - role: control-plane
      extraPortMappings:
        - containerPort: 30080
          hostPort: 30080
          protocol: TCP
        - containerPort: 30001
          hostPort: 30001
          protocol: TCP