FROM node:24-alpine

WORKDIR /app

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodejs -u 1001

COPY package*.json ./
RUN npm ci

COPY tsconfig.json ./
COPY src ./src

RUN npm run build

RUN rm -rf src tsconfig.json

USER nodejs

EXPOSE 3000

CMD ["node", "dist/index.js"]
