apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
data:
  NODE_ENV: "development"
  LOG_LEVEL: "debug"
  REDIS_URL: "redis://dev-redis:6379"
  NEXT_PUBLIC_SOCKET_URL: "http://localhost"
  NEXT_PUBLIC_API_URL: "http://localhost/api"
