version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: chat-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - chat-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: chat-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - USE_REDIS=true
      - FRONTEND_URL=http://localhost:3001
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/nest-cli.json:/app/nest-cli.json
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - chat-network
    restart: unless-stopped

networks:
    chat-network:
      driver: bridge

volumes:
  redis-data:
    driver: local
