kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: chat-app
nodes:
- role: control-plane
  extraPortMappings:
  # Ingress HTTP
  - containerPort: 30080
    hostPort: 80
    protocol: TCP
  # Ingress HTTPS
  - containerPort: 30443
    hostPort: 443
    protocol: TCP
  # Frontend NodePort (バックアップアクセス用)
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  # Backend NodePort (バックアップアクセス用)
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
