{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "next-nest-app.fullname" . }}-frontend
  labels:
    {{- include "next-nest-app.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "next-nest-app.frontend.selectorLabels" . | nindent 4 }}
{{- end }}