apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: nestjs_app
  POSTGRES_USER: nestjs_user
  POSTGRES_HOST_AUTH_METHOD: trust
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: bmVzdGpzX3Bhc3N3b3Jk