apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chat-app-dev

resources:
  - ../../base

namePrefix: dev-

labels:
  - pairs:
      environment: development

patches:
  - path: patches/configmap-patch.yaml
  - path: patches/backend-resources.yaml
  - path: patches/frontend-resources.yaml

replicas:
  - name: backend
    count: 1
  - name: frontend
    count: 1
  - name: redis
    count: 1
